In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/refs/heads/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv'

In [3]:
# !wget $data -O data-week-3.csv

In [4]:
df = pd.read_csv('data-week-3.csv')

In [5]:
df.columns = df.columns.str.lower().str.replace(' ','_')

In [6]:
df.T

0             1               2     \
customerid              7590-VHVEG    5575-GNVDE      3668-QPYBK   
gender                      Female          Male            Male   
seniorcitizen                    0             0               0   
partner                        Yes            No              No   
dependents                      No            No              No   
tenure                           1            34               2   
phoneservice                    No           Yes             Yes   
multiplelines     No phone service            No              No   
internetservice                DSL           DSL             DSL   
onlinesecurity                  No           Yes             Yes   
onlinebackup                   Yes            No             Yes   
deviceprotection                No           Yes              No   
techsupport                     No            No              No   
streamingtv                     No            No              No   
streamingmovies                 No            No              No   
contract            Month-to-month      One year  Month-to-month   
paperlessbilling               Yes            No             Yes   
paymentmethod     Electronic check  Mailed check    Mailed check   
monthlycharges               29.85         56.95           53.85   
totalcharges                 29.85        1889.5          108.15   
churn                           No            No             Yes   

                                       3                 4     \
customerid                       7795-CFOCW        9237-HQITU   
gender                                 Male            Female   
seniorcitizen                             0                 0   
partner                                  No                No   
dependents                               No                No   
tenure                                   45                 2   
phoneservice                             No               Yes   
multiplelines              No phone service                No   
internetservice                         DSL       Fiber optic   
onlinesecurity                          Yes                No   
onlinebackup                             No                No   
deviceprotection                        Yes                No   
techsupport                             Yes                No   
streamingtv                              No                No   
streamingmovies                          No                No   
contract                           One year    Month-to-month   
paperlessbilling                         No               Yes   
paymentmethod     Bank transfer (automatic)  Electronic check   
monthlycharges                         42.3              70.7   
totalcharges                        1840.75            151.65   
churn                                    No               Yes   

                              5                        6                 7     \
customerid              9305-CDSKC               1452-KIOVK        6713-OKOMC   
gender                      Female                     Male            Female   
seniorcitizen                    0                        0                 0   
partner                         No                       No                No   
dependents                      No                      Yes                No   
tenure                           8                       22                10   
phoneservice                   Yes                      Yes                No   
multiplelines                  Yes                      Yes  No phone service   
internetservice        Fiber optic              Fiber optic               DSL   
onlinesecurity                  No                       No               Yes   
onlinebackup                    No                      Yes                No   
deviceprotection               Yes                       No                No   
techsupport                     No               

In [7]:
categorical_columns = list(df.dtypes[df.dtypes == 'object'].index)
for c in categorical_columns:
    df[c] = df[c].str.lower().str.replace(' ','_')

In [8]:
tc = pd.to_numeric(df.totalcharges, errors='coerce')
df.totalcharges = tc.fillna(0)

In [9]:
df.churn

0        no
1        no
2       yes
3        no
4       yes
       ... 
7038     no
7039     no
7040     no
7041    yes
7042     no
Name: churn, Length: 7043, dtype: object

In [10]:
df.churn = (df.churn == 'yes').astype(int)

In [11]:
df.churn

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: churn, Length: 7043, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
len(df)

7043

In [14]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)

In [15]:
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)

In [16]:
len(df_train), len(df_val), len(df_test)

(4225, 1409, 1409)

In [17]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [18]:
y_train = df_train.churn.values
y_val = df_val.churn.values
y_test = df_test.churn.values

In [19]:
y_train, y_val, y_test

(array([0, 0, 1, ..., 1, 0, 1], shape=(4225,)),
 array([0, 0, 0, ..., 0, 1, 1], shape=(1409,)),
 array([0, 0, 0, ..., 0, 0, 1], shape=(1409,)))

In [20]:
del df_train['churn']
del df_val['churn']
del df_test['churn']

In [21]:
df_full_train = df_full_train.reset_index(drop=True)

In [22]:
df_full_train.churn.value_counts(), df_full_train.churn.value_counts(normalize=True)

(churn
 0    4113
 1    1521
 Name: count, dtype: int64,
 churn
 0    0.730032
 1    0.269968
 Name: proportion, dtype: float64)

In [23]:
global_churn_rate = df_full_train.churn.mean()
round(global_churn_rate, 2)

np.float64(0.27)

In [24]:
df_full_train.dtypes

customerid           object
gender               object
seniorcitizen         int64
partner              object
dependents           object
tenure                int64
phoneservice         object
multiplelines        object
internetservice      object
onlinesecurity       object
onlinebackup         object
deviceprotection     object
techsupport          object
streamingtv          object
streamingmovies      object
contract             object
paperlessbilling     object
paymentmethod        object
monthlycharges      float64
totalcharges        float64
churn                 int64
dtype: object

In [25]:
numerical = ['tenure', 'monthlycharges', 'totalcharges']
numerical

['tenure', 'monthlycharges', 'totalcharges']

In [26]:
df_full_train.columns

Index(['customerid', 'gender', 'seniorcitizen', 'partner', 'dependents',
       'tenure', 'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod', 'monthlycharges', 'totalcharges', 'churn'],
      dtype='object')

In [27]:
categorical = ['gender', 'seniorcitizen', 'partner', 'dependents',
       'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod']

In [28]:
df_full_train[categorical].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64

In [35]:
global_churn = df_full_train.churn.mean()

In [39]:
female_churn = df_full_train[df_full_train.gender == 'female'].churn.mean()

In [43]:
male_churn = df_full_train[df_full_train.gender == 'male'].churn.mean()

In [47]:
df_full_train.partner.value_counts()

partner
no     2932
yes    2702
Name: count, dtype: int64

In [54]:
partner_churn = df_full_train[df_full_train.partner == 'yes'].churn.mean()
no_partner_churn = df_full_train[df_full_train.partner == 'no'].churn.mean()

In [65]:
global_churn, female_churn, male_churn, partner_churn, no_partner_churn

(np.float64(0.26996805111821087),
 np.float64(0.27682403433476394),
 np.float64(0.2632135306553911),
 np.float64(0.20503330866025166),
 np.float64(0.3298090040927694))

In [77]:
from IPython.display import display

In [85]:
for c in categorical:
    formatted = c.upper()
    print(f"\033[1;4m{formatted}\033[0m")
    df_group = df_full_train.groupby(c).churn.agg(['mean','count'])
    df_group['diff'] = df_group['mean'] - global_churn
    df_group['risk'] = df_group['mean'] / global_churn
    display(df_group)
    print('*********************************************')
    print()
    print()

GENDER


mean  count      diff      risk
gender                                     
female  0.276824   2796  0.006856  1.025396
male    0.263214   2838 -0.006755  0.974980

*********************************************


SENIORCITIZEN


mean  count      diff      risk
seniorcitizen                                     
0              0.242270   4722 -0.027698  0.897403
1              0.413377    912  0.143409  1.531208

*********************************************


PARTNER


mean  count      diff      risk
partner                                     
no       0.329809   2932  0.059841  1.221659
yes      0.205033   2702 -0.064935  0.759472

*********************************************


DEPENDENTS


mean  count      diff      risk
dependents                                     
no          0.313760   3968  0.043792  1.162212
yes         0.165666   1666 -0.104302  0.613651

*********************************************


PHONESERVICE


mean  count      diff      risk
phoneservice                                     
no            0.241316    547 -0.028652  0.893870
yes           0.273049   5087  0.003081  1.011412

*********************************************


MULTIPLELINES


mean  count      diff      risk
multiplelines                                        
no                0.257407   2700 -0.012561  0.953474
no_phone_service  0.241316    547 -0.028652  0.893870
yes               0.290742   2387  0.020773  1.076948

*********************************************


INTERNETSERVICE


mean  count      diff      risk
internetservice                                     
dsl              0.192347   1934 -0.077621  0.712482
fiber_optic      0.425171   2479  0.155203  1.574895
no               0.077805   1221 -0.192163  0.288201

*********************************************


ONLINESECURITY


mean  count      diff      risk
onlinesecurity                                          
no                   0.420921   2801  0.150953  1.559152
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.153226   1612 -0.116742  0.567570

*********************************************


ONLINEBACKUP


mean  count      diff      risk
onlinebackup                                            
no                   0.404323   2498  0.134355  1.497672
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.217232   1915 -0.052736  0.804660

*********************************************


DEVICEPROTECTION


mean  count      diff      risk
deviceprotection                                        
no                   0.395875   2473  0.125907  1.466379
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.230412   1940 -0.039556  0.853480

*********************************************


TECHSUPPORT


mean  count      diff      risk
techsupport                                             
no                   0.418914   2781  0.148946  1.551717
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.159926   1632 -0.110042  0.592390

*********************************************


STREAMINGTV


mean  count      diff      risk
streamingtv                                             
no                   0.342832   2246  0.072864  1.269897
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.302723   2167  0.032755  1.121328

*********************************************


STREAMINGMOVIES


mean  count      diff      risk
streamingmovies                                         
no                   0.338906   2213  0.068938  1.255358
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.307273   2200  0.037305  1.138182

*********************************************


CONTRACT


mean  count      diff      risk
contract                                           
month-to-month  0.431701   3104  0.161733  1.599082
one_year        0.120573   1186 -0.149395  0.446621
two_year        0.028274   1344 -0.241694  0.104730

*********************************************


PAPERLESSBILLING


mean  count      diff      risk
paperlessbilling                                     
no                0.172071   2313 -0.097897  0.637375
yes               0.338151   3321  0.068183  1.252560

*********************************************


PAYMENTMETHOD


mean  count      diff      risk
paymentmethod                                                 
bank_transfer_(automatic)  0.168171   1219 -0.101797  0.622928
credit_card_(automatic)    0.164339   1217 -0.105630  0.608733
electronic_check           0.455890   1893  0.185922  1.688682
mailed_check               0.193870   1305 -0.076098  0.718121

*********************************************




In [76]:
df_group_partner = df_full_train.groupby('partner').churn.agg(['mean', 'count'])
df_group_partner['diff'] = df_group_partner['mean'] - global_churn
df_group_partner['risk'] = df_group_partner['mean'] / global_churn
df_group_partner

mean  count      diff      risk
partner                                     
no       0.329809   2932  0.059841  1.221659
yes      0.205033   2702 -0.064935  0.759472