In [100]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [101]:
# data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/refs/heads/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv'

In [102]:
# !wget $data -O data-week-3.csv

In [103]:
df = pd.read_csv('data-week-3.csv')

In [104]:
df.columns = df.columns.str.lower().str.replace(' ','_')

In [105]:
df.T

0             1               2     \
customerid              7590-VHVEG    5575-GNVDE      3668-QPYBK   
gender                      Female          Male            Male   
seniorcitizen                    0             0               0   
partner                        Yes            No              No   
dependents                      No            No              No   
tenure                           1            34               2   
phoneservice                    No           Yes             Yes   
multiplelines     No phone service            No              No   
internetservice                DSL           DSL             DSL   
onlinesecurity                  No           Yes             Yes   
onlinebackup                   Yes            No             Yes   
deviceprotection                No           Yes              No   
techsupport                     No            No              No   
streamingtv                     No            No              No   
streamingmovies                 No            No              No   
contract            Month-to-month      One year  Month-to-month   
paperlessbilling               Yes            No             Yes   
paymentmethod     Electronic check  Mailed check    Mailed check   
monthlycharges               29.85         56.95           53.85   
totalcharges                 29.85        1889.5          108.15   
churn                           No            No             Yes   

                                       3                 4     \
customerid                       7795-CFOCW        9237-HQITU   
gender                                 Male            Female   
seniorcitizen                             0                 0   
partner                                  No                No   
dependents                               No                No   
tenure                                   45                 2   
phoneservice                             No               Yes   
multiplelines              No phone service                No   
internetservice                         DSL       Fiber optic   
onlinesecurity                          Yes                No   
onlinebackup                             No                No   
deviceprotection                        Yes                No   
techsupport                             Yes                No   
streamingtv                              No                No   
streamingmovies                          No                No   
contract                           One year    Month-to-month   
paperlessbilling                         No               Yes   
paymentmethod     Bank transfer (automatic)  Electronic check   
monthlycharges                         42.3              70.7   
totalcharges                        1840.75            151.65   
churn                                    No               Yes   

                              5                        6                 7     \
customerid              9305-CDSKC               1452-KIOVK        6713-OKOMC   
gender                      Female                     Male            Female   
seniorcitizen                    0                        0                 0   
partner                         No                       No                No   
dependents                      No                      Yes                No   
tenure                           8                       22                10   
phoneservice                   Yes                      Yes                No   
multiplelines                  Yes                      Yes  No phone service   
internetservice        Fiber optic              Fiber optic               DSL   
onlinesecurity                  No                       No               Yes   
onlinebackup                    No                      Yes                No   
deviceprotection               Yes                       No                No   
techsupport                     No               

In [106]:
categorical_columns = list(df.dtypes[df.dtypes == 'object'].index)
for c in categorical_columns:
    df[c] = df[c].str.lower().str.replace(' ','_')

In [107]:
tc = pd.to_numeric(df.totalcharges, errors='coerce')
df.totalcharges = tc.fillna(0)

In [110]:
df.churn

0        no
1        no
2       yes
3        no
4       yes
       ... 
7038     no
7039     no
7040     no
7041    yes
7042     no
Name: churn, Length: 7043, dtype: object

In [112]:
df.churn = (df.churn == 'yes').astype(int)

In [113]:
df.churn

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: churn, Length: 7043, dtype: int64

In [114]:
from sklearn.model_selection import train_test_split

In [115]:
len(df)

7043

In [116]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)

In [117]:
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)

In [118]:
len(df_train), len(df_val), len(df_test)

(4225, 1409, 1409)

In [119]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [120]:
y_train = df_train.churn.values
y_val = df_val.churn.values
y_test = df_test.churn.values

In [121]:
y_train, y_val, y_test

(array([0, 0, 1, ..., 1, 0, 1], shape=(4225,)),
 array([0, 0, 0, ..., 0, 1, 1], shape=(1409,)),
 array([0, 0, 0, ..., 0, 0, 1], shape=(1409,)))

In [122]:
del df_train['churn']
del df_val['churn']
del df_test['churn']

In [123]:
df_full_train = df_full_train.reset_index(drop=True)

In [127]:
df_full_train.churn.value_counts(), df_full_train.churn.value_counts(normalize=True)

(churn
 0    4113
 1    1521
 Name: count, dtype: int64,
 churn
 0    0.730032
 1    0.269968
 Name: proportion, dtype: float64)

In [131]:
global_churn_rate = df_full_train.churn.mean()
round(global_churn_rate, 2)

np.float64(0.27)

In [132]:
df_full_train.dtypes

customerid           object
gender               object
seniorcitizen         int64
partner              object
dependents           object
tenure                int64
phoneservice         object
multiplelines        object
internetservice      object
onlinesecurity       object
onlinebackup         object
deviceprotection     object
techsupport          object
streamingtv          object
streamingmovies      object
contract             object
paperlessbilling     object
paymentmethod        object
monthlycharges      float64
totalcharges        float64
churn                 int64
dtype: object

In [134]:
numerical = ['tenure', 'monthlycharges', 'totalcharges']
numerical

['tenure', 'monthlycharges', 'totalcharges']

In [135]:
df_full_train.columns

Index(['customerid', 'gender', 'seniorcitizen', 'partner', 'dependents',
       'tenure', 'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod', 'monthlycharges', 'totalcharges', 'churn'],
      dtype='object')

In [136]:
categorical = ['gender', 'seniorcitizen', 'partner', 'dependents',
       'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod']

In [146]:
df_full_train[categorical].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64